- name: Install NGINX
  yum:
    name: nginx
    state: present

- name: Start NGINX
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy website
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    mode: '0644'
    force: yes

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
